language: python

python:
  - "3.7"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.7
      install:
        - cd ./lab2/
        - pipenv install
      script: pipenv run pytest tests/tests.py || true
    - stage: "Build Lab 3."
      name: "Run Djungo Server and test it accessibility. Fail to run and test"
      python: 3.7
      install:
        - cd ./lab3/
        - pipenv install
      script: ./scripts/travis-build.sh
    - stage: "Build Lab 4."
      name: "Build Docker images"
      services:
        - docker
      install:
        - cd ./lab4/
      script:
        - docker build -t bobas/lab4-examples:django .
        - docker images
    - stage: "Build Lab 5."
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./lab5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
branches:
  only:
    - master